[package]
namespace = "SherkeyXD"
name = "Maimai Sounds"
description = "A mod that replaces some default sound effects with musics/effects from maimai DX."
websiteUrl = "https://github.com/SherkeyXD/Maimai-Sounds"

[publish]
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["asset-replacements", "mods", "bepinex", "audio", "boombox", "clientside", "items"]
