name: Publish

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Setup tcli
        run: dotnet tool install -g tcli

      - name: Make zip
        run: zip -r MaimaiSounds-${{ github.ref_name }}.zip . -x='.git/*' -x='.github/*' -x='thunderstore.toml'

      - name: Publish to Thunderstore
        run: |
          tcli publish --file MaimaiSounds-${{ github.ref_name }}.zip --token ${{ secrets.TCLI_AUTH_TOKEN }}
      
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: MaimaiSounds-${{ github.ref_name }}.zip